<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Think-Pad" failures="2" tests="5" name="Test" time="0.074" errors="0" timestamp="2023-05-13T19:26:12 EDT">
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestFive" time="0.014"/>
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestFour" time="0.001"/>
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestOne" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.ny.hooks.FailedTestCases.getTestOne(FailedTestCases.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestOne -->
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestThree" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.ny.hooks.FailedTestCases.getTestThree(FailedTestCases.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestThree -->
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestTwo" time="0.001"/>
</testsuite> <!-- Test -->
